### ISSUE TITLE
Compile issue latest release

### ISSUE THREAD

**Issue by mfkilgore** [graphaware/neo4j-nlp-stanfordnlp#24]
Started with git pull for neo4j-nlp, clean, install no issues found
Compile issue in neo4j-nlp-stanfordnlp in StanfordTextProcessor
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project nlp-stanfordnlp: Compilation failure: Compilation failure:
[ERROR] /Users/mfkilgore/IdeaProjects/GraphAware/neo4j-nlp-stanfordnlp/src/main/java/com/graphaware/nlp/processor/stanford/StanfordTextProcessor.java:[57,8] com.graphaware.nlp.processor.stanford.StanfordTextProcessor is not abstract and does not override abstract method annotateTags(java.lang.String,java.lang.String,com.graphaware.nlp.dsl.request.PipelineSpecification) in com.graphaware.nlp.processor.TextProcessor
[ERROR] /Users/mfkilgore/IdeaProjects/GraphAware/neo4j-nlp-stanfordnlp/src/main/java/com/graphaware/nlp/processor/stanford/StanfordTextProcessor.java:[104,5] method does not override or implement a method from a supertype
[ERROR] /Users/mfkilgore/IdeaProjects/GraphAware/neo4j-nlp-stanfordnlp/src/main/java/com/graphaware/nlp/processor/stanford/StanfordTextProcessor.java:[438,5] method does not override or implement a method from a supertype
[ERROR] /Users/mfkilgore/IdeaProjects/GraphAware/neo4j-nlp-stanfordnlp/src/main/java/com/graphaware/nlp/processor/stanford/StanfordTextProcessor.java:[456,5] method does not override or implement a method from a supertype
[ERROR] /Users/mfkilgore/IdeaProjects/GraphAware/neo4j-nlp-stanfordnlp/src/main/java/com/graphaware/nlp/processor/stanford/StanfordTextProcessor.java:[561,5] method does not override or implement a method from a supertype

**Comment by ikwattro** [comment]
Hi @mfkilgore , when you mean latest release, are you checking out the tags of the release or the master branch ?

**Comment by mfkilgore** [comment]
@ikwattro sorry I should have been more clear.  I am using the master branch for both projects.

**Comment by ikwattro** [comment]
Well, don't build master :) 

You can build from the `develop` branch in both neo4j-nlp and stanford

**Comment by mfkilgore** [comment]
Thank you, that works perfectly
